# Generated by Django 5.1.1 on 2024-10-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_data_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_shipped',
            new_name='date_shipped',
        ),
    ]
